---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
suites:
  - name: default
    run_list:
      - recipe[chef_vault_users::default]
    attributes: {
      users: {
        test_user: {
          password: 'password', 
          password_is_plain: true,
          ssh_keys: 'this is not a key'
        }
      }
    }

settings:
  parallel: true
